version: '3'
services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - mysql-datavolume:/var/lib/mysql
  mongo:
    image: mongo
    volumes:
         - mongodb-datavolume:/data/db
  delayedjob:
    build:
      context: .
      dockerfile: Dockerfile-staging
    command: rake RAILS_ENV=staging jobs:work
    volumes:
      - .:/app
    depends_on:
      - mongo
      - db
    environment:
      - RACK_ENV=staging
      - RAILS_ENV=staging
  app:
    build:
      context: .
      dockerfile: Dockerfile-staging
    volumes:
      - .:/app
    depends_on:
      - mongo
      - db
    environment:
      - RACK_ENV=staging
      - RAILS_ENV=staging
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"
volumes:
  mysql-datavolume:
  mongodb-datavolume:
