version: '3'
services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - mysql-datavolume:/var/lib/mysql
  mongo:
    image: mongo
    volumes:
         - mongodb-datavolume:/data/db
  web:
    build:
      context: .
      dockerfile: Dockerfile-staging
    volumes:
      - .:/app
      - assets:/app/public/assets
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - db
    environment:
      - RACK_ENV=staging
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - web
    ports:
      - "80:80"
volumes:
  mysql-datavolume:
  mongodb-datavolume:
  assets:
