<%
  @path = "#{Rubber.root}/config/database.yml"
%>

<%= Rubber.env %>:
  adapter: <%= YAML::load(File.open("#{Rubber.root}/config/database.yml.example"))[Rubber.env]["adapter"] %>
  encoding: utf8
  database: <%= rubber_env.db_name %>
  username: root
  password: 
  host: localhost
  pool: 5
