community_name: "Redu"
community_tagline: "A Rede Social Educacional"
community_description:  "A Rede Social Educacional"
community_url : "http://www.redu.com.br"
support_email:  "support@community.com"
meta_description: 'A description of your community for use in META tags.'
meta_keywords: 'keywords for use in META tags'
sections_enabled: ['photos', 'posts', 'clippings', 'contests', 'categories', 'events']
show_advertising: false
closed_beta_mode: false
# Comment this out if you want to infer the locale
# off of the http headers
community_locale: "pt-BR"

# The label you use for 'staff' writers (featured writer, staff, pro, etc.)
allow_anonymous_commenting: false
require_captcha_on_signup: false
#recaptcha_pub_key: YOUR_PUB_KEY
#recaptcha_priv_key: YOUR_PRIV_KEY
# uncomment these keys if you turn captcha on for commenting or signup

# for SEO reasons sometime you should control the robots on how they have to handle your content
# listing of stuff which points to single posts or entries should normally not been indexed, 
# but the robot should follow the internal link to show the post
robots_meta_list_content: 'noindex,follow'
# the post itself should be indexed; 
# when links are included and they point to external sites, the robot should not follow
robots_meta_show_content: 'index,nofollow'
items_per_page: 3
comments_number: 15

points:
  created_course: 80
  updated_course: 15
  show_course: 10
  created_exam: 40
  updated_exam: 15
  show_exam: 10
  created_resource: 30
  show_resource: 15
  answer_exam: 20

image:
  #missing_thumb: '/images/icon_missing_thumb.gif'
  #missing_medium: "/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    #min_size: 1    
    #size in megabytes
    max_size: 3
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

photo:
  missing_thumb: '/images/icon_missing_thumb.gif'
  missing_medium: "/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    #size in megabytes
    max_size: 3
    thumbnails: {thumb: "c100x100!", medium: "c290x320!", large: "664>"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
      
feature:
  use_thumbs: true
  dimensions: [150, 635]
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    max_size: 1
    thumbnails: {thumb: 'c45x45!', large: 'c635x150!'}    
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
        
clipping:
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    max_size: 3
    thumbnails: {thumb: "c100x100!", medium_square: "c200x200!", medium: "200>"}
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
    
reserved_logins: [
  'about', 
  'account', 
  'advertise', 
  'ads', 
  'application', 
  'assets', 
  'categories', 
  'choices', 
  'clippings', 
  'clipping_images', 
  'comments', 
  'contests', 
  'countries', 
  'css_help', 
  'events', 
  'favorites', 
  'faq', 
  'featured', 
  'forums', 
  'friendships', 
  'friendship_statuses', 
  'home', 
  'homepage_features', 
  'images', 
  'invitations', 
  'javascripts', 
  'login', 
  'logout', 
  'manage_photos', 
  'messages', 
  'metro_areas', 
  'moderatorships', 
  'new_clipping',  
  'offerings', 
  'photos', 
  'polls', 
  'popular', 
  'popular_rss', 
  'posts', 
  'recent', 
  'roles', 
  'search', 
  'signup', 
  'sb_posts', 
  'skills', 
  'sitemap', 
  'states',
  'stylesheets', 
  'tags', 
  'theme', 
  'topics', 
  'users', 
  'votes']
