community_name: "Redu"
community_tagline: "A Rede Social Educacional"
community_description:  "A Rede Social Educacional"
community_url : "http://beta.redu.com.br"
support_email:  "contato@redu.com.br"
contact_emails: "contato@redu.com.br"
meta_description: 'A description of your community for use in META tags.'
meta_keywords: 'keywords for use in META tags'
# for SEO reasons sometime you should control the robots on how they have to handle your content
# listing of stuff which points to single posts or entries should normally not been indexed,
# but the robot should follow the internal link to show the post
robots_meta_list_content: 'noindex,follow'
# the post itself should be indexed;
# when links are included and they point to external sites, the robot should not follow
robots_meta_show_content: 'index,nofollow'


# Comment this out if you want to infer the locale
# off of the http headers
community_locale: "pt-BR"

# The label you use for 'staff' writers (featured writer, staff, pro, etc.)
require_captcha_on_signup: false
#recaptcha_pub_key: YOUR_PUB_KEY
#recaptcha_priv_key: YOUR_PRIV_KEY
# uncomment these keys if you turn captcha on for commenting or signup

# setup
closed_beta_mode: true
show_constellation: false
activate_payment: false
show_advertising: false

items_per_page: 10
users_per_page: 10
desc_char_limit: 200
attachments_number: 6
max_lesson_number: 10
moderate: ['Exam', 'InteractiveClass', 'Seminar']

points:
  created_lecture: 80
  updated_lecture: 15
  show_lecture: 10
  created_exam: 40
  updated_exam: 15
  show_exam: 10
  answer_exam: 20
  created_resource: 30
  show_resource: 15


image:
  #missing_thumb: '/images/icon_missing_thumb.gif'
  #missing_medium: "/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    #min_size: 1
    #size in megabytes
    max_size: 3
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

photo:
  missing_thumb: '/images/missing_pic.jpg' #'/images/icon_missing_thumb.gif'
  missing_medium: '/images/missing_pic.jpg' #"/images/icon_missing_medium.gif"
  missing_thumb_space: '/images/missing_pic_space.png' #'/images/icon_missing_thumb.gif'
  missing_medium_space: '/images/missing_pic_space.png' #"/images/icon_missing_medium.gif"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1
    #size in megabytes
    max_size: 3
    thumbnails: {thumb: "c100x100!", medium: "c290x320!", large: "664>"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 'file_system'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']



reserved_logins: [
  'about',
  'account',
  'admin',
  'advertise',
  'ads',
  'application',
  'assets',
  'access_keys',
  'beta_keys',
  'beta',
  'blog',
  'categories',
  'choices',
  'clippings',
  'clipping_images',
  'comments',
  'contests',
  'countries',
  'credits',
  'css_help',
  'events',
  'exams',
  'exames',
  'favorites',
  'faq',
  'featured',
  'forums',
  'friendships',
  'friendship_statuses',
  'home',
  'homepage_features',
  'images',
  'invitations',
  'javascripts',
  'login',
  'logout',
  'lessons',
  'manage_photos',
  'messages',
  'metro_areas',
  'moderatorships',
  'new_clipping',
  'offerings',
  'photos',
  'polls',
  'popular',
  'popular_rss',
  'posts',
  'recent',
  'redu',
  'resources',
  'roles',
  'search',
  'seminars',
  'seminarios',
  'signup',
  'sb_posts',
  'spaces',
  'skills',
  'sitemap',
  'states',
  'stylesheets',
  'tags',
  'theme',
  'topics',
  'users',
  'votes']
