s3_access_key_id: AKIAIRKVQDTWT2NN4J4Q
s3_secret_access_key: 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
s3_permission: public_read
s3_bucket: redu-assets-staging
s3_upload_files:
  - public/images/new/**
  - public/javascripts/**
  - public/stylesheets/**

javascripts:
  common:
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/jquery.tipTip.minified.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css
    - public/stylesheets/new-fonts.css
    - public/stylesheets/new-style.css
    - public/stylesheets/tipTip.css
    - public/stylesheets/ajaxful_rating.css


