embed_assets: on
s3_cache_control: 432000
s3_access_key_id: AKIAIRKVQDTWT2NN4J4Q
s3_secret_access_key: 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
s3_permission: public_read
s3_bucket: redu-assets
s3_upload_files:
  - public/images/new/**
  - public/javascripts/**
  - public/javascripts/ckeditor/**/**/**/*
  - public/stylesheets/**

javascripts:
  common:
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/jquery.tipTip.minified.js
    - public/javascripts/folders.js
    - public/javascripts/lectures.js
    - public/javascripts/swfobject.js
    - public/javascripts/jquery.form.js
    - public/javascripts/jquery.remotipart.js
    - public/javascripts/lazyload.js

  chat:
    - public/javascripts/jquery.pjax.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/pusher.js
    - public/javascripts/chat.js
    - public/javascripts/jquery.json.js
    - public/javascripts/jquery.cookie.js
  ie:
    - public/javascripts/selectivizr.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css
    - public/stylesheets/new-fonts.css
    - public/stylesheets/new-style.css
    - public/stylesheets/tipTip.css
    - public/stylesheets/ajaxful_rating.css
  ie:
    - public/stylesheets/ie.css

  chat:
    - public/stylesheets/chat.css
