embed_assets: on
s3_cache_control: 432000
s3_access_key_id: AKIAIRKVQDTWT2NN4J4Q
s3_secret_access_key: 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
s3_permission: public_read
s3_bucket: redu-assets
s3_upload_files:
  - public/images/new/**
  - public/javascripts/**
  - public/javascripts/ckeditor/**/**/**/*
  - public/stylesheets/**

javascripts:
  lazyload: &lazyload
    - public/javascripts/lazyload.js
    - public/javascripts/asyncjs.jquery.js
  webview:
    - public/javascripts/vendor/jquery.js
    - *lazyload
  invite_friend:
    - public/javascripts/jquery.tokeninput-invite-friend.js
    - public/javascripts/friend-invitation.js
  bootstrap: &bootstrap
    - public/javascripts/rails.js
    - public/javascripts/vendor/modernizr.js
    - public/javascripts/jquery.autosize.min.js
    - public/javascripts/vendor/placeholder-polyfill.min.js
    - public/javascripts/bootstrap-redu.js
  chat:
    - public/javascripts/jquery.pjax.js
    - public/javascripts/pusher.js
    - public/javascripts/jquery.json.js
    - public/javascripts/jquery.linkify-1.0.js
    - public/javascripts/chat.jquery.js
    - public/javascripts/chat.js
    - public/javascripts/loading.js
  user:
    - public/javascripts/jquery.maskedinput.js
  canvas:
    - public/javascripts/easyXDM.js
    - public/javascripts/canvas.js
  olark:
    - public/javascripts/olark.js

stylesheets:
  chat:
    - public/stylesheets/chat.css
  print:
    - public/stylesheets/reset.css
    - public/stylesheets/new-fonts.css
    - public/stylesheets/new-style.css
    - public/stylesheets/print.css
  page:
    - public/stylesheets/reset.css
    - public/stylesheets/new-fonts.css
