development:
  adapter: mysql2
  username: root
  password:
  database: redu_development
  host: localhost

staging:
  adapter: mysql2
  username: root
  password:
  database: redu_staging
  host: localhost

production:
  adapter: mysql2
  username: root
  password:
  database: redu_production
  host: localhost

test:
  adapter: mysql2
  username: root
  password:
  database: redu_test
  host: localhost
