environments:
  production: &production
    copy_exclude:
      - .git
    branch: master
    migrate: false
    migration_command: rake db:migrate --trace
  staging: &staging
    copy_exclude:
      - .git
    branch: staging
    migrate: false
    migration_command: rake db:migrate --trace
  staging_rails3:
    <<: *staging
