defaults:
  precompile_assets: true
  assets_strategy: cleaning
  copy_exclude:
    - .git
  migrate: false
  migration_command: rake db:migrate --trace
  asset_roles:
    - :app
    - :app_master
    - :util
environments :
  production: &production
    branch: master
  staging: &staging
    branch: staging
