environments:
  production:
    copy_exclude:
      - .git
    branch: production
    migrate: false
    migration_command: rake db:migrate --trace
  staging:
    copy_exclude:
      - .git
    branch: refactor
    migrate: false
    migration_command: rake db:migrate --trace
