development:
  sessions:
    default:
      database: redu_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: redu_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: redu_development
      hosts:
        - localhost:27017
