development: &development
  developer: true
  base: "http://0.0.0.0:3000"
  return_to: "/payment/callback"
  email: guilhermec@redu.com.br

test:
  <<: *development

performance:
  <<: *development

production:
  authenticity_token: 4F79E50AF51F4F1FB06964D1A1A4679C
  return_to: "/payment/callback"
  email: guilhermec@redu.com.br

staging:
  authenticity_token: 4F79E50AF51F4F1FB06964D1A1A4679C
  return_to: "/payment/callback"
  email: guilhermec@redu.com.br
