development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/payment/success"
  email: guilhermec@redu.com.br

test:
  <<: *development

production:
  authenticity_token: 4F79E50AF51F4F1FB06964D1A1A4679C
  return_to: "/payment/success"
  email: guilhermec@redu.com.br

production:
  authenticity_token: 4F79E50AF51F4F1FB06964D1A1A4679C
  return_to: "/payment/success"
  email: guilhermec@redu.com.br
