development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/payment/success"
  email: guilhermec@redu.com.br

test:
  <<: *development

production:
  authenticity_token: 9CA8D46AF0C6177CB4C23D76CAF5E4B0
  email: user@example.com
  return_to: "/pedido/efetuado"
