staging:
  access_key_id: AKIAIRKVQDTWT2NN4J4Q
  secret_access_key: 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
  bucket: redu_uploads_staging
  files_bucket: redu_files_staging

production:
  access_key_id: AKIAIRKVQDTWT2NN4J4Q
  secret_access_key: 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
  bucket: redu_uploads
  files_bucket: redu_files

development:
  access_key_id: AKIAIRKVQDTWT2NN4J4Q
  secret_access_key: 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
  bucket: redu_assets_development
  
backup:
  aws_access_key: 'AKIAIRKVQDTWT2NN4J4Q'
  aws_secret_access_key: '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'
  options: 
    use_ssl: false
