defaults: &defaults
  access_key_id: 1PA6KRGRS1JAYMRN8D02
  secret_access_key: 6XQILMvuzBoYKp8YkzoFjafNxG0AvhjdmyLZIQGW

staging: &staging
  <<: *defaults
  bucket: redu-uploads-staging
  videos_bucket: redu-uploads-staging
  files_bucket: redu-uploads-staging
  assets_bucket: redu-assets-staging

production:
  <<: *defaults
  bucket: redu_uploads2
  videos_bucket: redu-videos2
  files_bucket: redu_files2
  assets_bucket: redu-assets2

development:
  <<: *defaults
  assets_bucket: redu-assets-staging

performance:
  <<: *defaults

test:
  <<: *defaults
