defaults: &defaults
  access_key_id: AKIAIIFN6QDFV6UCXTYA
  secret_access_key: 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

staging: &staging
  <<: *defaults
  bucket: openredu-uploads-staging
  videos_bucket: openredu-uploads-staging
  files_bucket: openredu-uploads-staging
  assets_bucket: openredu-assets-staging

production:
  <<: *defaults
  bucket: openredu-uploads-production
  videos_bucket: openredu-videos-production
  files_bucket: openredu-files-production
  assets_bucket: openredu-assets-production

development:
  <<: *defaults
  assets_bucket: openredu-assets-staging

performance:
  <<: *defaults

test:
  <<: *defaults
