#TODO deve estar havendo algum problema.
pt-BR:
    courses: "aulas"
    new: "criar" 
    edit: "editar"
    lessons: "topicos"
    exams: "exames"
    schools: "redes"
    users: "pessoas"
    Users: "usuarios"
    show_favorites: "favoritos"
    favorites: "favoritos"
    owner: "dono"
    member: "membro"
    folders: "arquivos"
    manage: "gerenciar"
    unjoin: "abandonar"
    join: "entrar"
    look_and_feel: "aparencia"
    moderate: "moderacao"
    administrator: "administracao"
    admin_members: "membros_pendentes"
    admin_requests: "solicitacoes_pendentes"
    admin_submissions: "submissoes_pendentes"
    