pt-BR:
    administrator: "administracao"
    admin_members: "admin_membros"
    admin_requests: "admin_solicitacoes"
    admin_submissions: "admin_submissoes"
    answer: "responder"
    courses: "aulas"
    contact: "contato"
    edit: "editar"
    exams: "exames"
    favorites: "favoritos"
    folders: "arquivos"
    invite: "convidar"
    join: "entrar"
    learn: "aprenda"
    lessons: "topicos"
    look_and_feel: "aparencia"
    manage: "gerenciar"
    member: "membro"
    members: "membros"
    moderate: "moderacao"
    new: "criar" 
    owner: "dono"
    results: "resultado"
    schools: "redes"
    show_favorites: "favoritos"
    signup: "registrar"
    #submissions : "submissões"
    teach: "ensine"
    unjoin: "abandonar"
    users: "pessoas"
    
    
    