graphite_dir: "/opt/graphite"
graphite_server_pid_file: /var/run/graphite-server.pid
graphite_server_port: 2003
graphite_web_port: 2080
graphite_carbon_port: 8002
graphite_storage_dir: /mnt/graphite_storage

# uncomment out the repo version to install from given repo version
# graphite_repo_version: 426
graphite_version: '0.9.12'
graphite_whisper_package_url: "https://github.com/graphite-project/whisper/archive/#{graphite_version}.tar.gz"
graphite_carbon_package_url: "https://github.com/graphite-project/carbon/archive/#{graphite_version}.tar.gz"
graphite_web_package_url: "https://github.com/graphite-project/graphite-web/archive/#{graphite_version}.tar.gz"

web_tools_proxies:
  graphite:
    role: graphite_web
    port: "#{graphite_web_port}"
    path: /

roles:
  graphite_web:
    os_packages:
      '12.04': [python-django, python-django-tagging, python-cairo, python-memcache, memcached, uwsgi, uwsgi-plugin-python, uwsgi-plugin-http, sqlite3, bzr, zip]
      '14.04': [uwsgi, uwsgi-plugin-python, graphite-web]
  graphite_server:
    os_packages:
      '14.04': [graphite-carbon]
  collectd:
    packages: [libperl-dev]

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graphite_web_secret: bac43040040472b03b202796c11e39b6af3eaef7eb88da2a7ec635de541a6637f938f03b267e84068875c30e17727c4c6eccbe6a4bc774c03d95cbe0cbf855069463210c3268981ba1173ef37ef23c9715421ad0b232b6c78d2aed0864156ca0
